services:
  chessgpt-web:
    container_name: sky-chessgpt-web
    image: ghcr.io/911218sky/chessgpt:web-support
    pull_policy: always
    environment:
      NGINX_LLM_PROXY_AUTHORIZATION: ${NGINX_LLM_PROXY_AUTHORIZATION:-}
      NGINX_LLM_PROXY_TARGET: ${NGINX_LLM_PROXY_TARGET:-https://www.inroi.shop/v1/}
    ports:
      - "5432:80"
    restart: unless-stopped
